name: flutter_service
description: Demonstrates how to use the flutter_local_notifications plugin.
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^14.1.1


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


 
flutter:
  uses-material-design: true
 # assets:
    # - icons/
    # - sound/


